travis:
  secure:
    BINSTAR_TOKEN: 0FZsZA42RhCGhfZskruMtEadKbhp8zyyIyDyzU4Jms9XxvKTLllQHYTt5rApFH3ndlyRWtlHG9MFRK17LLbP0eGKV2x0snG4Twn0kZWHlqPfA43d7HEQxmkAe6LurjM4KOESQAXC868If9xC49Cz1fgUmTtNw7wFdJYHZvKA0Dg3gie3Y/wz6f9FgpmSLxoFt1EQHqcQ3Tboaodu02b5Rslnv7vynoVSdkN2W1x83fGn1O9Fsnls+TM31nRVtGbJGTGPvRj+h/YjjsK1giVJssLKH4jydo+wwMCybzKNO35n0F0mYetyqf1YuFUNG+onYTpyjwTM2pzOPtvLHQcvFgrcH2xFbnrZblWpxiHU07E/Lgen98IkXgW+Hn948IsmY7KDfbyUYQkOqQpS0CWsfnfG/+f6r+GtfLkGxvxtfLmsHimXZ2BwG33BLFzpRdg4uThgk1tuV3hRt38h03burWGiTUIwegSNpkINRBVbtR5h9ByAaRrGWntPcYJhM192x9gsdADi24c+e7ryHlgiYb/IKeAup/QO6QRegvFPKQBmuue20mdkWsxKPY1UnZsy6g51Y1EaGX89dxtXTgqXz6P61Dorqi9lDLKIszyabfjHLaXwFwBdDKUyLibz4WmFmDPbXSEgCpdbNxfldu6Un+zmJfnQIj6tBU81ZRWLCGc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
